[global]
locale = "{locale}"

[[pageStyle]]
name = "{project.template.pageStyleCard}"
behavior = "CARD"

[[pageStyle]]
name = "{project.template.pageStyleScroll}"
behavior = "SCROLL"
scrollMeltWithNext = true

[[contentStyle]]
name = "{project.template.contentStyleHeading}"
bodyLetterStyleName = "{project.template.letterStyleBig}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleSubheading}"
bodyLetterStyleName = "{project.template.letterStyleSmall}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleGutter}"
blockOrientation = "HORIZONTAL"
spineAttachment = "HEAD_GAP_CENTER"
bodyLetterStyleName = "{project.template.letterStyleBigBold}"
bodyLayout = "GRID"
gridElemBoxConform = "WIDTH"
gridElemHJustifyPerCol = "LEFT"
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"
headHJustify = "RIGHT"
headVJustify = "TOP"
headGapPx = 24.0

[[contentStyle]]
name = "{project.template.contentStyleBullets}"
bodyLetterStyleName = "{project.template.letterStyleBigBold}"
bodyLayout = "FLOW"
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"

[[contentStyle]]
name = "{project.template.contentStyleLogos}"
bodyLetterStyleName = "{project.template.letterStyleBigBold}"
bodyLayout = "FLOW"
flowElemBoxConform = "SQUARE"
flowLineWidthPx = 1200.0
flowLineGapPx = 32.0
flowHGapPx = 32.0
flowSeparator = ""

[[contentStyle]]
name = "{project.template.contentStyleBlurb}"
bodyLetterStyleName = "{project.template.letterStyleBig}"
bodyLayout = "PARAGRAPHS"
paragraphsLineWidthPx = 400.0

[[contentStyle]]
name = "{project.template.contentStyleCard}"
bodyLetterStyleName = "{project.template.letterStyleCardBigBold}"
bodyLayout = "GRID"
gridElemBoxConform = "WIDTH"
hasHead = true
headLetterStyleName = "{project.template.letterStyleCardSmall}"
headGapPx = 32.0
hasTail = true
tailLetterStyleName = "{project.template.letterStyleCardSmall}"
tailGapPx = 32.0

[[letterStyle]]
name = "{project.template.letterStyleBigBold}"
fontName = "Archivo Narrow Bold"
heightPx = 32

[[letterStyle]]
name = "{project.template.letterStyleBig}"
fontName = "Archivo Narrow Regular"
heightPx = 32

[[letterStyle]]
name = "{project.template.letterStyleSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 24

[[letterStyle]]
name = "{project.template.letterStyleCardBigBold}"
fontName = "Archivo Narrow Bold"
heightPx = 100

[[letterStyle]]
name = "{project.template.letterStyleCardSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 50
