[global]
locale = "{locale}"

[[pageStyle]]
name = "{project.template.pageStyleCard}"
behavior = "CARD"

[[pageStyle]]
name = "{project.template.pageStyleScroll}"
behavior = "SCROLL"
scrollMeltWithNext = true

[[contentStyle]]
name = "{project.template.contentStyleHeading}"
bodyLetterStyleName = "{project.template.letterStyleHeading}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleSubheading}"
bodyLetterStyleName = "{project.template.letterStyleSmall}"
bodyLayout = "GRID"

[[contentStyle]]
name = "{project.template.contentStyleGutter}"
blockOrientation = "HORIZONTAL"
spineAttachment = "HEAD_GAP_CENTER"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "GRID"
gridMatchColWidths = "ACROSS_BLOCKS"
gridCellHJustifyPerCol = ["LEFT"]
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"
headMatchWidth = "ACROSS_BLOCKS"
headHJustify = "RIGHT"
headVJustify = "TOP"
headGapPx = 24.0

[[contentStyle]]
name = "{project.template.contentStyleBullets}"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "FLOW"
flowLineWidthPx = 800.0
hasHead = true
headLetterStyleName = "{project.template.letterStyleSmall}"

[[contentStyle]]
name = "{project.template.contentStyleTabular}"
bodyLetterStyleName = "{project.template.letterStyleName}"
bodyLayout = "GRID"
gridStructure = "EQUAL_WIDTH_COLS"
gridCellHJustifyPerCol = ["LEFT", "CENTER", "RIGHT"]

[[contentStyle]]
name = "{project.template.contentStyleSong}"
bodyLetterStyleName = "{project.template.letterStyleSmall}"
bodyLayout = "GRID"
hasHead = true
headLetterStyleName = "{project.template.letterStyleSongTitle}"
headGapPx = 0.0

[[contentStyle]]
name = "{project.template.contentStyleLogos}"
bodyLetterStyleName = "{project.template.letterStyleNormal}"
bodyLayout = "FLOW"
flowSquareCells = true
flowLineWidthPx = 1200.0
flowLineGapPx = 32.0
flowHGapPx = 32.0
flowSeparator = ""

[[contentStyle]]
name = "{project.template.contentStyleBlurb}"
bodyLetterStyleName = "{project.template.letterStyleNormal}"
bodyLayout = "PARAGRAPHS"
paragraphsLineWidthPx = 500.0

[[contentStyle]]
name = "{project.template.contentStyleCard}"
bodyLetterStyleName = "{project.template.letterStyleCardName}"
bodyLayout = "GRID"
hasHead = true
headLetterStyleName = "{project.template.letterStyleCardSmall}"
headGapPx = 32.0
hasTail = true
tailLetterStyleName = "{project.template.letterStyleCardSmall}"
tailGapPx = 32.0

[[letterStyle]]
name = "{project.template.letterStyleNormal}"
fontName = "Archivo Narrow Regular"
heightPx = 32

[[letterStyle]]
name = "{project.template.letterStyleSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 24

[[letterStyle]]
name = "{project.template.letterStyleHeading}"
fontName = "Archivo Narrow Regular"
heightPx = 32
trackingEm = 0.05

[[letterStyle.decorations]]
preset = "OFF"
offsetPx = 5.0
thicknessPx = 2.0

[[letterStyle]]
name = "{project.template.letterStyleName}"
fontName = "Archivo Narrow Bold"
heightPx = 32

[[letterStyle]]
name = "{project.template.letterStyleSongTitle}"
fontName = "Archivo Narrow Bold"
heightPx = 32
smallCaps = "SMALL_CAPS"

[[letterStyle]]
name = "{project.template.letterStyleCardName}"
fontName = "Archivo Narrow Bold"
heightPx = 100

[[letterStyle]]
name = "{project.template.letterStyleCardSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 50
