
[global]
fps = "24/1"
widthPx = 1920
heightPx = 1080
background = "#000000"
unitVGapPx = 32.0

[[pageStyle]]
name = "Card"
behavior = "CARD"
afterwardSlugFrames = 24
cardDurationFrames = 96
cardFadeInFrames = 12
cardFadeOutFrames = 12

[[pageStyle]]
name = "Scroll"
behavior = "SCROLL"
afterwardSlugFrames = 24
scrollPxPerFrame = 3.0

[[contentStyle]]
name = "Card"
vMarginPx = 0.0
centerOn = "EVERYTHING"
spineDir = "VERTICAL"
colsBodyLayoutColJustifies = "CENTER"
colsBodyLayoutColGapPx = 30.0
bodyFontSpec = "Archivo Narrow Bold 100 #ffffff"
headHJustify = "CENTER"
headGapPx = 30.0
headFontSpec = "Archivo Narrow Regular 50 #ffffff"
tailHJustify = "CENTER"
tailGapPx = 30.0
tailFontSpec = "Archivo Narrow Regular 50 #ffffff"

[[contentStyle]]
name = "Collection"
vMarginPx = 0.0
centerOn = "EVERYTHING"
spineDir = "VERTICAL"
colsBodyLayoutColJustifies = "LEFT"
flowBodyLayoutBodyWidthPx = 1000.0
flowBodyLayoutJustify = "CENTER"
flowBodyLayoutSeparator = "•"
flowBodyLayoutSeparatorSpacingPx = 14.0
bodyFontSpec = "Archivo Narrow Bold 32 #ffffff"
headHJustify = "CENTER"
headGapPx = 8.0
headFontSpec = "Archivo Narrow Regular 24 #ffffff"

[[contentStyle]]
name = "Gutter"
vMarginPx = 0.0
centerOn = "HEAD_GAP"
spineDir = "HORIZONTAL"
colsBodyLayoutColJustifies = "LEFT"
colsBodyLayoutColGapPx = 30.0
bodyFontSpec = "Archivo Narrow Bold 32 #ffffff"
headHJustify = "RIGHT"
headVJustify = "TOP_MIDDLE"
headGapPx = 24.0
headFontSpec = "Archivo Narrow Regular 24 #ffffff"

[[contentStyle]]
name = "Heading"
vMarginPx = 0.0
centerOn = "EVERYTHING"
spineDir = "VERTICAL"
colsBodyLayoutColJustifies = "CENTER"
colsBodyLayoutColGapPx = 30.0
bodyFontSpec = "Archivo Narrow Regular 32 #ffffff"

[[contentStyle]]
name = "Subheading"
vMarginPx = 0.0
centerOn = "EVERYTHING"
spineDir = "VERTICAL"
colsBodyLayoutColJustifies = "CENTER"
colsBodyLayoutColGapPx = 30.0
bodyFontSpec = "Archivo Narrow Regular 24 #ffffff"

