[[pageStyle]]
name = "{project.defaults.pageStyleCard}"
behavior = "CARD"

[[pageStyle]]
name = "{project.defaults.pageStyleScroll}"
behavior = "SCROLL"

[[contentStyle]]
name = "{project.defaults.contentStyleHeading}"
bodyLayout = "GRID"
bodyLetterStyleName = "{project.defaults.letterStyleBig}"

[[contentStyle]]
name = "{project.defaults.contentStyleSubheading}"
bodyLayout = "GRID"
bodyLetterStyleName = "{project.defaults.letterStyleSmall}"

[[contentStyle]]
name = "{project.defaults.contentStyleGutter}"
spineOrientation = "HORIZONTAL"
alignWithAxis = "HEAD_GAP_CENTER"
bodyLayout = "GRID"
bodyLayoutElemConform = "WIDTH"
bodyLayoutColsHJustify = "LEFT"
bodyLetterStyleName = "{project.defaults.letterStyleBigBold}"
headHJustify = "RIGHT"
headVJustify = "TOP"
headGapPx = 24.0
headLetterStyleName = "{project.defaults.letterStyleSmall}"

[[contentStyle]]
name = "{project.defaults.contentStyleBullets}"
bodyLayout = "FLOW"
bodyLetterStyleName = "{project.defaults.letterStyleBigBold}"
headLetterStyleName = "{project.defaults.letterStyleSmall}"

[[contentStyle]]
name = "{project.defaults.contentStyleLogos}"
bodyLayout = "FLOW"
bodyLayoutLineGapPx = 32.0
bodyLayoutElemConform = "SQUARE"
bodyLayoutHorizontalGapPx = 32.0
bodyLayoutBodyWidthPx = 1200.0
bodyLayoutSeparator = ""
bodyLetterStyleName = "{project.defaults.letterStyleBigBold}"

[[contentStyle]]
name = "{project.defaults.contentStyleBlurb}"
bodyLayout = "PARAGRAPHS"
bodyLayoutBodyWidthPx = 400.0
bodyLetterStyleName = "{project.defaults.letterStyleBig}"

[[contentStyle]]
name = "{project.defaults.contentStyleCard}"
bodyLayout = "GRID"
bodyLayoutElemConform = "WIDTH"
bodyLetterStyleName = "{project.defaults.letterStyleCardBigBold}"
headGapPx = 32.0
headLetterStyleName = "{project.defaults.letterStyleCardSmall}"
tailGapPx = 32.0
tailLetterStyleName = "{project.defaults.letterStyleCardSmall}"

[[letterStyle]]
name = "{project.defaults.letterStyleBigBold}"
fontName = "Archivo Narrow Bold"
heightPx = 32

[[letterStyle]]
name = "{project.defaults.letterStyleBig}"
fontName = "Archivo Narrow Regular"
heightPx = 32

[[letterStyle]]
name = "{project.defaults.letterStyleSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 24

[[letterStyle]]
name = "{project.defaults.letterStyleCardBigBold}"
fontName = "Archivo Narrow Bold"
heightPx = 100

[[letterStyle]]
name = "{project.defaults.letterStyleCardSmall}"
fontName = "Archivo Narrow Regular"
heightPx = 50
